export const jsonData = [
  {
    id: 0,
    title: "Storytelling and Teaching",
    desc: "Aren't stories wonderful? Let’s think about it for a minute, stories are everywhere..",
    image:"images/image2.jpeg",
    content:
      "Aren't stories wonderful? Let’s think about it for a minute,stories are everywhere. \n\n As kids, our grandparents would share stuff with us through the mediums of stories. How shiny were the summer times, when we gotto hear incidents from their lives in the forms of most hilarious stories! Back in elementary classes, our teachers would converse with us through stories. We ourselves narrated everyday incidents to our parents as stories! \n\n Where did it go, that innocence, that curiosity, that understanding of concepts? I suggest, and all of us would agree that, conversing through stories, made concepts easier to understand.\n Also, when I think about it, we were easily able to grasp morals and themes of stories and folklores, but most of us struggled with lessons. How did this happen that we remember morals of stories even now, but not essence of chapters from schools days?\n\n Certain studies on the internet suggests us that, the ability to retain stories is an evolutionary process. Our ancestors, would scribble on the walls to express and share their daily lives to their fellow companions. Stories not only inspires us but teaches us morals that are unforgettable. Imagine if we could get the characters of any story to take maths lectures for us, or, animated heroes to teach us history or science? \n\n Certainly, just the idea of content being narrated to us, sounds good as it can also help to create a bond between teacher and students in any school.\n\n While I understand, not everything can be story-lined, there are definitely benefits to it that can add to a healthy content delivery for students of even higher classes. Storytelling can \n\n* Instil virtues and values in a child\n * Elevatea student’s listening skills\n * Deepen a child’s imagination\n * Help them build their communication skills\n* Make learning easier \n * Improve social skills and interactional relationships \n* Help explain difficult concepts It just doesn’t end there. \n\n It just doesn’t end there. Storytelling has been found to be one of the effective most teaching strategy in European countries. So why shouldn’t we also try? Let’s share some stories and see if we can explain our fellow being important lessons of life. Because, if we all can relate to stories, then, so will a student.",
    date: "May 16, 2023",
  },

  {
    id: 1,
    title: " A tip for an Effective Storytelling",
    desc: "In the Guru-Shishya parampara, Gurus would sit in front of their students to impart..",
    image:"images/image1.jpeg",
    content:
      "In the Guru-Shishya parampara, Gurus would sit in front of their students to impart them with lessons worth in their lives. The group would recite mantras, explore forests, mediate for inner calmness and consume natural fruits when hungry. All these activities set in motion a synergy between the Guru and his Shishya. In the modern times, replicating this exact process would be slightly challenging due to the involvement of modern lifestyle and newer rules of society. However, one of the things that cannot be replaced is the bond between a teacher and a student,  between a mentor and mantee, between a coach and a player, and that is the bond formed through stories. \n\n Just like we discussed about benefits of storytelling in our previous letter, this letter is all about Effective storytelling. \n\nWhy should there be a need for storytelling, what can I and you as learners and knowledge imparting individual get out it? The short answer is Connection. A synergy. \nThe long answer however, can be understood from previous week’s letter, so please feel free to dive into the benefits of storytelling in teaching. \n\nFor us to strike a better understanding, let me share with you an acronym that is quite famous in terms of storytelling. Feel empowered to use, “STORY”:\n\nS: Setting of the act \n T: Theme of the lesson to be taught \n O: Objective of the story \n R: Resolution/Reason of the story \n Y: Your lesson/moral from the story \n\n Every lesson that we know as it, can be taught through the medium of ‘STORY’. One should clearly know what they are looking to impart, hence the Theme of the lesson. The Theme should be set in a direction that introduces characters, the scene or more specifically the Setting of the act. \n\n The scene would empower characters and characters with names will help the students feel comfortable, relatable. And yes be sure, do know the concrete “why”, or the Resolution of your story. Once the reason is clear the Moral from the story would naturally flow. \n\n So, in a nutshell, plan a scene, introduce characters, know the lesson, know the reason for the story and finally conclude with a Moral or a key takeaway for the listeners.",
    date: "May 16, 2023",
  },
  {
    id: 2,
    title: "Storytelling and Studying",
    desc: "No claps can be made with one hand. My Naani ( Ammama) taught me that.As a kid..",
    image:"images/image0.jpeg",
    content:
      "No claps can be made with one hand. My Naani ( Ammama) taught me that. As a kid, I would always look for creating win-win, because to my understanding that was the easy lesson. However how could I create a Win and another if the other person actually doesn’t know if they were winning? What if I was dealing with kids younger to me? I could easily trick them for my benefit knowingly or unknowingly.\nAs kids roam with brimming innocence, no matter what ever taught to them would trick them into believing its for their advantage. After all, its not until we grow up that we start asking ‘Why’ behind every thing. \n\n If we are to inculcate storytelling in our education system and impart better knowledge to our creative-curious children, we must clap with both hands. As in, we do it first and then call them upon to continue with the same. \n\n The benefits of storytelling is not all too far to be known. We have already shared some Light on it and even fired a Laser on a tip to better tell a story by using “STORY”. Feel free to dive back into the contents of those posts. \n\n Now as teachers and parents, if we make an effort to better educate our students and children by storytelling, then, a better way to make an impact would be to ask them to do it too. Ultimately, we must clap with two hands. One us, one them. Together it is an essential element that is being changed. \n\n We can either do this activity either with topics from our textbook chapters or with a different idea in itself. Either ways, let me help you with the details:\n\n 1. Start: help your children have a start, or a prompt to give them the first step. Its you extending your hands for clapping. By doing this, you provide them with a little motivation to engage them. Students are quick and creative to elaborate more on it by themselves. \n\n 2. Content with Creativity: no matter how young, we as humans are filled with creativity. Once you have initiated the clap, let them also reciprocate it back by showcasing their creativity. Appreciate them, motivate them and above all help them use the beauty of storytelling to learn better. You can adapt the “STORY” method (discussed in previous newsletter) and shape it for them as well. \n\n 3. Listen, to them. : Providing feedbacks is an essential component of learning. It allows us to improve our abilities to perform better. Once a student is speaking, listen engagingly by asking questions and providing feedback in the end if necessary. When other students would see you doing it, they would also get engaged and this would perfectly improve the quality of your classroom experience. The clap has taken place now. \n\n As parents and educators we can always improve by engaging better. Storytelling is an effective methodology that is a boon from our Culture. Lets create a win-win. And as someone rightly said, no claps can be made with one hand.",
    date: "May 16, 2023",
  },
  // {
  //   id: 3,
  //   title: "Storytelling and Teaching",
  //   desc: "In the Guru-Shishya parampara, Gurus would sit in front of their students to impart..",
  //   image:"images/image0.jpeg",
  //   content:
  //     "Aren't stories wonderful? Let’s think about it for a minute,stories are everywhere.\n As kids, our grandparents would share stuff with us through themediums of stories. How shiny were the summer times, when we gotto hear incidents from their lives in the forms of most hilariousstories! Back in elementary classes, our teachers would converse with us through stories. We ourselves narrated everyday incidents to our parents as stories!\n\n Where did it go, that innocence, that curiosity, that understanding of concepts? I suggest, and all of us would agree that, conversing through stories, made concepts easier to understand.\n Also, when I think about it, we were easily able to grasp morals and themes of stories and folklores, but most of us struggled with lessons. How did this happen that we remember morals of stories even now, but not essence of chapters from schools days?\n\n Certain studies on the internet suggests us that, the ability to retain stories is an evolutionary process. Our ancestors, would scribble on the walls to express and share their daily lives to their fellow companions. Stories not only inspires us but teaches us morals that are unforgettable. Imagine if we could get the characters of any story to take maths lectures for us, or, animated heroes to teach us history or science? \n\n Certainly, just the idea of content being narrated to us, sounds good as it can also help to create a bond between teacher and students in any school.\n\n While I understand, not everything can be story-lined, there are definitely benefits to it that can add to a healthy content delivery for students of even higher classes. Storytelling can \n\n* Instil virtues and values in a child\n * Elevatea student’s listening skills\n * Deepen a child’s imagination\n * Help them build their communication skills\n* Make learning easier \n * Improve social skills and interactional relationships \n* Help explain difficult concepts It just doesn’t end there. \n\n It just doesn’t end there. Storytelling has been found to be one of the effective most teaching strategy in European countries. So why shouldn’t we also try? Let’s share some stories and see if we can explain our fellow being important lessons of life. Because, if we all can relate to stories, then, so will a student.",
  //   date: "May 16, 2023",
  // },
  // {
  //   id: 4,
  //   title: " A tip for an Effective Storytelling",
  //   desc: "In the Guru-Shishya parampara, Gurus would sit in front of their students to impart..",
  //   image:"images/image0.jpeg",
  //   content:
  //     "Aren't stories wonderful? Let’s think about it for a minute,stories are everywhere.\n As kids, our grandparents would share stuff with us through themediums of stories. How shiny were the summer times, when we gotto hear incidents from their lives in the forms of most hilariousstories! Back in elementary classes, our teachers would converse with us through stories. We ourselves narrated everyday incidents to our parents as stories!\n\n Where did it go, that innocence, that curiosity, that understanding of concepts? I suggest, and all of us would agree that, conversing through stories, made concepts easier to understand.\n Also, when I think about it, we were easily able to grasp morals and themes of stories and folklores, but most of us struggled with lessons. How did this happen that we remember morals of stories even now, but not essence of chapters from schools days?\n\n Certain studies on the internet suggests us that, the ability to retain stories is an evolutionary process. Our ancestors, would scribble on the walls to express and share their daily lives to their fellow companions. Stories not only inspires us but teaches us morals that are unforgettable. Imagine if we could get the characters of any story to take maths lectures for us, or, animated heroes to teach us history or science? \n\n Certainly, just the idea of content being narrated to us, sounds good as it can also help to create a bond between teacher and students in any school.\n\n While I understand, not everything can be story-lined, there are definitely benefits to it that can add to a healthy content delivery for students of even higher classes. Storytelling can \n\n* Instil virtues and values in a child\n * Elevatea student’s listening skills\n * Deepen a child’s imagination\n * Help them build their communication skills\n* Make learning easier \n * Improve social skills and interactional relationships \n* Help explain difficult concepts It just doesn’t end there. \n\n It just doesn’t end there. Storytelling has been found to be one of the effective most teaching strategy in European countries. So why shouldn’t we also try? Let’s share some stories and see if we can explain our fellow being important lessons of life. Because, if we all can relate to stories, then, so will a student.",
  //   date: "May 16, 2023",
  // },
  // {
  //   id: 5,
  //   title: "Storytelling and Studying",
  //   desc: "In the Guru-Shishya parampara, Gurus would sit in front of their students to impart..",
  //   image:"images/image0.jpeg",
  //   content:
  //     "Aren't stories wonderful? Let’s think about it for a minute,stories are everywhere.\n As kids, our grandparents would share stuff with us through themediums of stories. How shiny were the summer times, when we gotto hear incidents from their lives in the forms of most hilariousstories! Back in elementary classes, our teachers would converse with us through stories. We ourselves narrated everyday incidents to our parents as stories!\n\n Where did it go, that innocence, that curiosity, that understanding of concepts? I suggest, and all of us would agree that, conversing through stories, made concepts easier to understand.\n Also, when I think about it, we were easily able to grasp morals and themes of stories and folklores, but most of us struggled with lessons. How did this happen that we remember morals of stories even now, but not essence of chapters from schools days?\n\n Certain studies on the internet suggests us that, the ability to retain stories is an evolutionary process. Our ancestors, would scribble on the walls to express and share their daily lives to their fellow companions. Stories not only inspires us but teaches us morals that are unforgettable. Imagine if we could get the characters of any story to take maths lectures for us, or, animated heroes to teach us history or science? \n\n Certainly, just the idea of content being narrated to us, sounds good as it can also help to create a bond between teacher and students in any school.\n\n While I understand, not everything can be story-lined, there are definitely benefits to it that can add to a healthy content delivery for students of even higher classes. Storytelling can \n\n* Instil virtues and values in a child\n * Elevatea student’s listening skills\n * Deepen a child’s imagination\n * Help them build their communication skills\n* Make learning easier \n * Improve social skills and interactional relationships \n* Help explain difficult concepts It just doesn’t end there. \n\n It just doesn’t end there. Storytelling has been found to be one of the effective most teaching strategy in European countries. So why shouldn’t we also try? Let’s share some stories and see if we can explain our fellow being important lessons of life. Because, if we all can relate to stories, then, so will a student.",
  //   date: "May 16, 2023",
  // },
];
